use serde::{Deserialize, Serialize};

use super::message::Message;

/// A session summary generated by LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub session_id: String,
    pub user_id: String,
    pub summary: String,
    pub key_points: Vec<String>,
    pub token_count: usize,
    pub message_count: usize,
    pub created_at: u64,
    pub updated_at: u64,
}

/// A full session snapshot for export.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSnapshot {
    pub session_id: String,
    pub messages: Vec<Message>,
    pub summary: Option<SessionSummary>,
}
